version: '2'
services:
  postgres:
    container_name: postgres
    image: arm64v8/postgres
    ports:
      - "5432:5432"
    env_file:
      - docker.env
    volumes:
      - 'db:/var/lib/postgresql/data'

  # pgadmin:
  #   # links:
  #   #   - postgres
  #   container_name: pgadmin
  #   image: dpage/pgadmin4:latest
  #   ports:
  #     - "8081:80"
  #   env_file:
  #     - docker.env

  backend:
    links:
      - postgres
    build: 
      context: ./atem-server
    expose:
      - "3000"
    ports:
      - "3000:3000"
      - 1935:1935
      - "443:443"
      - 5678:5678
      - 1259:1259
    env_file:
      - docker.env
    depends_on:
      - postgres

  frontend:
    build:
      context: ./atem-client
    expose:
      - "3000"
      - "8080"
      - "80"
    ports:
      - "8080:3000"
      - "80:80"

networks:
  default:
    driver: bridge

volumes:
  db:
