version: '2.1'
volumes:
    postgres-data:
    pgadmin-data:
services:
#  postgres:
#    container_name: postgres
#    image: arm32v7/postgres
#    ports:
#      - "5432:5432"
#    env_file:
#      - docker.env
#    networks:
#      - postgres
#    volumes:
#      - "postgres-data:/var/lib/postgresql/data"
#
#  pgadmin:
#    links:
#      - postgres:postgresstgres:
  ##    container_name: postgres
  ##    image: arm32v7/postgres
  ##    ports:
  ##      - "5432:5432"
  ##    env_file:
  ##      - docker.env
  ##    networks:
  ##      - postgres
  ##    volumes:
  ##      - "postgre
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    ports:
#      - "8081:80"
#    env_file:
#      - docker.env
#    networks:
#      - postgres
#    volumes:
#      - "pgadmin-data:/root/.pgadmin"

#  backend:
#    build: ./atem-server
#    expose:
#      - "3000"
#    ports:
#      - "3000:3000"
#      - 1935:1935
#    network_mode: bridge

  restreamer:
    image: datarhei/restreamer-armv7l:latest
    container_name: restreamer
    expose:
      - "8080"
      - "1935"
    ports:
      - "8080:8080"
      - "1935:1935"
    environment:
      - RS_USERNAME=admin
      - RS_PASSWORD=admin
      - RS_TIMEZONE=Australia/Sydney
      - RS_TOKEN=wPtYpe2di
    tmpfs:
      - /tmp/hls

#fblive:
#    image: dweomer/stunnel
#    container_name: fblive
#    expose:
#      - 1935
#    networks:
#      - frontend
#    restart: always
#    environment:
#      - STUNNEL_SERVICE=fb-live
#      - STUNNEL_CLIENT=yes
#      - STUNNEL_ACCEPT=1935
#      - STUNNEL_CONNECT=live-api-s.facebook.com:443
#      - STUNNEL_VERIFY_CHAIN=NO

#  frontend:
#    build: ./frontend
#    expose:
#      - "80"
#  proxy:
#    build: ./haproxy
#    depends_on:
#      - frontend
#      - data
#    ports:
#      - "80:80"
#  data:
#    build: ./data
#    expose:
#      - "8080"