version: "3"
services:
  postgres:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/data/postgres
    env_file:
      - docker.env

  pgadmin:
    links:
      - postgres
    container_name: postgresadmin
    image: dpage/pgadmin4
    ports:
      - "8081:80"
    volumes:
      - ./data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env

  backend:
    links:
      - postgres
    build: 
      context: ./atem-server
      dockerfile: Dockerfile
    expose:
      - "3000"
    ports:
      - "3000:3000"
      - 1935:1935
      - "443:443"
      - 5678:5678
      - 1259:1259
    volumes:
      - './atem-server:/app'
      - '/app/node_modules'
    env_file:
      - docker.env
    depends_on:
      - postgres
    links:
      - 'postgres:database'

  frontend:
    build:
      context: ./atem-client
      dockerfile: Dockerfile.prod
    expose:
      - "3000"
    ports:
      - "8080:3000"
    volumes:
      - '.:/app'
      - '/app/node_modules'

networks:
  default:
    driver: bridge
