version: '2.1'
services:
  backend:
    build: ./atem-server
    expose:
      - "3000"
    ports:
      - "3000:3000"
    network_mode: bridge

#  frontend:
#    build: ./frontend
#    expose:
#      - "80"
#  proxy:
#    build: ./haproxy
#    depends_on:
#      - frontend
#      - data
#    ports:
#      - "80:80"
#  data:
#    build: ./data
#    expose:
#      - "8080"